### ISSUE TITLE
Bod plaatsen.

### ISSUE THREAD

**Issue by WouterHoltslag** [thijs1108/EenmaalAndermaal#5]
Het plaatsen van een bod kan alleen als het bedrag hoger is dan elk geboden bedrag.
Voorbeeld:
Voorwerp 1 heeft een hoogste bieding van €10,00
Voorwerp 2 heeft een hoogste bieding van €15,00

Nu is het niet mogelijk om bij voorwerp 1 €12,00 te bieden. Pas als er €16 wordt geboden wordt het weggeschreven in de database. Heeft te maken met de trigger die op de database zit

**Comment by thijs1108** [comment]
Haha lol, zelfde probleem als die Max 4 foto's wss. Ik ga het z.s.m. fixen, kleine ingreep waarschijnlijk

**Comment by thijs1108** [comment]
fixed in 42cd6d4
