### ISSUE TITLE
Feedback Systeem

### ISSUE THREAD

**Issue by WouterHoltslag** [thijs1108/EenmaalAndermaal#6]
We moeten het feedback systeem ook nog maken/bedenken.

**Comment by thijs1108** [comment]
Klopt, dit wordt waarschijnlijk met dezelfde trigger gedaan als het sluiten van een voorwerp, kan dus Hierna worden opgelost

**Comment by thijs1108** [comment]
feedback systeem gaat @MFJLBeuzel slopen :hammer: :bomb:  :boom:
